version: 2.1

orbs:
  cypress: cypress-io/cypress@1

workflows:
  test-deploy:
    jobs:
      - test
       - cypress/install:
            command: cd client && npm i
        - cypress/run:
            name: Chrome
            yarn: true
            requires:
              - cypress/install
            executor: with-chrome
            browser: chrome
            record: true
        - cypress/run:
            name: Firefox
            yarn: true
            requires:
              - cypress/install
            executor: with-firefox
            browser: firefox
            record: true

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    working_directory: ~/client

    steps:
      - checkout
      - run:
          name: install dependencies
          command: cd client && npm i
      - run:
          name: run tests
          command: cd client && npm run test
