version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    working_directory: ~/client

    steps:
      - checkout

      - run:
          name: install dependencies
          command: cd client && npm i
      - run:
          name: run tests
          command: cd client && npm run test
