version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/node:16.18.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker-login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image
          command: docker push $IMAGE_NAME
      - run:
          name: set-environment-variables
          command: echo $SERVER > server.crt && echo $PRIVATE_KEY > privatekey.pem
      - run:
          name: build-docker-image-for-integration-environment
          command: docker create -p 3000:3000 --name integration_app $IMAGE_NAME
      - run:
          name: copy-server-cert-and-private-key-across
          command: docker cp ./privatekey.pem integration_app:/privatekey.pem; docker cp ./server.crt integration_app:/server.crt
      - run:
          name: start-docker-container
          command: docker start integration_app

  deploy:
    docker:
      - image: circleci/node:16.18.1
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf OPUS/"
