version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    working_directory: ~/client

    steps:
      - checkout

      - run:
          name: ls
          command: ls

      - run:
          name: cd
          command: cd client

      - run:
        name: ls
        command: ls

      - run:
        name: pwd
        command: pwd

      - run:
          name: switch folders
          command: cd client
      - run:
          name: install dependencies
          command: npm i
      - run:
          name: run tests
          command: npm run test
